apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: flux-demo
spec:
  encryptedData:
    secret: AgA7VaIpCsk+w/pLvSJvk7+BvCgDqKcFWI0kaYnWzb3vSoixcpa1zdkBpj0t8ufm1hD5jbWyLMAlvP+vYnNjYPU6aPV2u6pcUFKUJOdyDx4Vgt5UjOlar2dgL/fjlGoHXt+nCNgiJYPZMBBHEtWLthrHjQ5KXtNdXND3If2+B9vT1c/kSUWS6OTd2E4b8aHFpL6nmTQrp2o+QngAFpREDpb4+6qbc6DCi2vvae/1QQf9nHsn6rsNCStqg4wap2bVVhFmwBIEcKSBrUNO/28j2vFPL7tz1vrQGm/cJ/kLnzKa8gP/MtfxgWbnw1EYFOY3SBjwaIhyIWF6OzXMKLIlK3WDShJCtzLdQ7Tlr5zJkdDCTovKJXlYC0c+5bMF0nW8jm1xUcoKnD1sPjcsDOHZp/3f5peY+OGxPIzpRTgsQECSxdyKuh2i1tkqXA54Mq+d5td1AFoXP9dX2M0ss0kVyA14CuO/emWzPfai2+B49KRrYQWTXDd5VS9peYMNDmDzEceEZW1IcJsiZhg2Dtxi/yisNklD3qVJCPKrYuMVwtUzQt8jMj3GVsHqHsNqpo9Z/yeCRAAovkh9oHh53mnryFgmS8xM+2JLtoPmVCSw49Im17Hj8EJyru+da+QPvm0LytSZMqo52mHH1+W++5ShyT9UAknElAGfgCVAFsFp/HGPh2yB+NEuNq6kO0tFBg08lhama/5mr1cc2frqIWk3mn2C
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: flux-demo
